hp=read.table("household_power_consumption.txt", sep=";", header=TRUE, na.strings="?")
hp$date=as.Date(hp$Date,"%d/%m/%Y")
hp$time=strptime(hp$Time, "%H:%M:%S")
hpc=subset(hp, hp$date>="2007-02-01")
png(filename="plot1.png", width=480, height=480)
hist(hp$Global_active_power, col="red", xlab= "Global Active Power (kilowatts)", main= "Global Active Power")
dev.off()