hp=read.table("household_power_consumption.txt", sep=";", header=TRUE, na.strings="?")
hp$date=as.Date(hp$Date,"%d/%m/%Y")
hp$time=strptime(hp$Time, "%H:%M:%S")
hpc=subset(hp, hp$date>="2007-02-01")
a=paste(hp$date, hp$Time)
t=as.POSIXct(a)
plot(t, hp$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering", main="")
lines(t, hp$Sub_metering_2, col="red")
lines(t, hp$Sub_metering_3, col="blue")
legend("topright", col=c("black", "red", "blue"), lty=1, lwd=2, 
       legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))